import uvicorn
from fastapi import FastAPI
from pydantic import BaseModel
import logging
from llm_client import generate_command

# 配置日志
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger("auto-shell-daemon")

app = FastAPI(title="auto-shell Daemon")

class SuggestionRequest(BaseModel):
    query: str
    cwd: str
    os: str
    shell: str

class SuggestionResponse(BaseModel):
    command: str
    explanation: str = ""

@app.post("/v1/suggest", response_model=SuggestionResponse)
async def get_suggestion(request: SuggestionRequest):
    logger.info(f"Received request: {request.query} in {request.cwd}")
    
    # 构造上下文
    context = {
        "cwd": request.cwd,
        "os": request.os,
        "shell": request.shell
    }
    
    # 调用 LLM 客户端生成命令
    command = await generate_command(request.query, context)
    
    # 如果 LLM 调用失败或返回空，提供一个友好的提示
    if not command:
        command = "echo 'auto-shell: 无法生成命令，请检查 API 配置或网络连接'"
        
    return SuggestionResponse(
        command=command,
        explanation="Generated by LLM."
    )

@app.get("/health")
async def health_check():
    return {"status": "ok"}

def start_daemon(host="0.0.0.0", port=28001):
    logger.info(f"Starting auto-shell daemon on {host}:{port}")
    uvicorn.run(app, host=host, port=port, log_level="info")

if __name__ == "__main__":
    start_daemon()
